// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StadiumTicketBooking.Data.Entity;

#nullable disable

namespace StadiumTicketBooking.Migrations
{
    [DbContext(typeof(StadiumDbContext))]
    partial class StadiumDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StadiumTicketBooking.Data.Entity.Ghe", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("KhuVucID")
                        .HasColumnType("int");

                    b.Property<string>("SoGhe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("KhuVucID");

                    b.ToTable("Ghe");
                });

            modelBuilder.Entity("StadiumTicketBooking.Data.Entity.HoaDon", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KhachHangID")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayLap")
                        .HasColumnType("datetime2");

                    b.Property<int>("NhanVienID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("KhachHangID");

                    b.HasIndex("NhanVienID");

                    b.ToTable("HoaDon");
                });

            modelBuilder.Entity("StadiumTicketBooking.Data.Entity.HoaDon_ChiTiet", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("DonGiaBan")
                        .HasColumnType("int");

                    b.Property<int>("HoaDonID")
                        .HasColumnType("int");

                    b.Property<int>("VeID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("HoaDonID");

                    b.HasIndex("VeID");

                    b.ToTable("HoaDon_ChiTiet");
                });

            modelBuilder.Entity("StadiumTicketBooking.Data.Entity.KhachHang", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DienThoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoVaTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("KhachHang");
                });

            modelBuilder.Entity("StadiumTicketBooking.Data.Entity.KhuVuc", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<double>("HeSoGia")
                        .HasColumnType("float");

                    b.Property<int>("SanVanDongID")
                        .HasColumnType("int");

                    b.Property<string>("TenKhuVuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("SanVanDongID");

                    b.ToTable("KhuVuc");
                });

            modelBuilder.Entity("StadiumTicketBooking.Data.Entity.NhanVien", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("DienThoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoVaTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VaiTroID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("VaiTroID");

                    b.ToTable("NhanVien");
                });

            modelBuilder.Entity("StadiumTicketBooking.Data.Entity.SanVanDong", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenSan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("SanVanDong");
                });

            modelBuilder.Entity("StadiumTicketBooking.Data.Entity.SuKien", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("GiaCoBan")
                        .HasColumnType("int");

                    b.Property<int>("SanVanDongID")
                        .HasColumnType("int");

                    b.Property<string>("TenSuKien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ThoiGian")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("SanVanDongID");

                    b.ToTable("SuKien");
                });

            modelBuilder.Entity("StadiumTicketBooking.Data.Entity.VaiTro", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("TenVaiTro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("VaiTro");
                });

            modelBuilder.Entity("StadiumTicketBooking.Data.Entity.Ve", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("GheID")
                        .HasColumnType("int");

                    b.Property<int>("GiaVe")
                        .HasColumnType("int");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SuKienID")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("GheID");

                    b.HasIndex("SuKienID");

                    b.ToTable("Ve");
                });

            modelBuilder.Entity("StadiumTicketBooking.Data.Entity.Ghe", b =>
                {
                    b.HasOne("StadiumTicketBooking.Data.Entity.KhuVuc", "KhuVuc")
                        .WithMany("Ghe")
                        .HasForeignKey("KhuVucID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhuVuc");
                });

            modelBuilder.Entity("StadiumTicketBooking.Data.Entity.HoaDon", b =>
                {
                    b.HasOne("StadiumTicketBooking.Data.Entity.KhachHang", "KhachHang")
                        .WithMany("HoaDon")
                        .HasForeignKey("KhachHangID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StadiumTicketBooking.Data.Entity.NhanVien", "NhanVien")
                        .WithMany("HoaDon")
                        .HasForeignKey("NhanVienID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("StadiumTicketBooking.Data.Entity.HoaDon_ChiTiet", b =>
                {
                    b.HasOne("StadiumTicketBooking.Data.Entity.HoaDon", "HoaDon")
                        .WithMany("HoaDon_ChiTiet")
                        .HasForeignKey("HoaDonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StadiumTicketBooking.Data.Entity.Ve", "Ve")
                        .WithMany()
                        .HasForeignKey("VeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HoaDon");

                    b.Navigation("Ve");
                });

            modelBuilder.Entity("StadiumTicketBooking.Data.Entity.KhuVuc", b =>
                {
                    b.HasOne("StadiumTicketBooking.Data.Entity.SanVanDong", "SanVanDong")
                        .WithMany("KhuVuc")
                        .HasForeignKey("SanVanDongID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SanVanDong");
                });

            modelBuilder.Entity("StadiumTicketBooking.Data.Entity.NhanVien", b =>
                {
                    b.HasOne("StadiumTicketBooking.Data.Entity.VaiTro", "VaiTro")
                        .WithMany("NhanVien")
                        .HasForeignKey("VaiTroID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VaiTro");
                });

            modelBuilder.Entity("StadiumTicketBooking.Data.Entity.SuKien", b =>
                {
                    b.HasOne("StadiumTicketBooking.Data.Entity.SanVanDong", "SanVanDong")
                        .WithMany("SuKien")
                        .HasForeignKey("SanVanDongID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SanVanDong");
                });

            modelBuilder.Entity("StadiumTicketBooking.Data.Entity.Ve", b =>
                {
                    b.HasOne("StadiumTicketBooking.Data.Entity.Ghe", "Ghe")
                        .WithMany()
                        .HasForeignKey("GheID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StadiumTicketBooking.Data.Entity.SuKien", "SuKien")
                        .WithMany("Ve")
                        .HasForeignKey("SuKienID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ghe");

                    b.Navigation("SuKien");
                });

            modelBuilder.Entity("StadiumTicketBooking.Data.Entity.HoaDon", b =>
                {
                    b.Navigation("HoaDon_ChiTiet");
                });

            modelBuilder.Entity("StadiumTicketBooking.Data.Entity.KhachHang", b =>
                {
                    b.Navigation("HoaDon");
                });

            modelBuilder.Entity("StadiumTicketBooking.Data.Entity.KhuVuc", b =>
                {
                    b.Navigation("Ghe");
                });

            modelBuilder.Entity("StadiumTicketBooking.Data.Entity.NhanVien", b =>
                {
                    b.Navigation("HoaDon");
                });

            modelBuilder.Entity("StadiumTicketBooking.Data.Entity.SanVanDong", b =>
                {
                    b.Navigation("KhuVuc");

                    b.Navigation("SuKien");
                });

            modelBuilder.Entity("StadiumTicketBooking.Data.Entity.SuKien", b =>
                {
                    b.Navigation("Ve");
                });

            modelBuilder.Entity("StadiumTicketBooking.Data.Entity.VaiTro", b =>
                {
                    b.Navigation("NhanVien");
                });
#pragma warning restore 612, 618
        }
    }
}
